/**
 * Task Tree Snapshot Types
 *
 * Defines the file format for saving and loading orchestration task trees.
 * Trees are saved to: projects/{project}/tasks/completed/{task_id}.json
 */

export interface AgentMetadata {
  /** Agent's thinking/reasoning (for planning nodes) */
  thoughts?: string;

  /** Code generated by agent (for coding agents) */
  code?: string;

  /** Agent's output/results */
  output?: string;

  /** General content/documentation */
  content?: string;

  /** Review findings (for AR agents) */
  review?: {
    status: 'approved' | 'needs_changes';
    issues: Array<{
      severity: 'critical' | 'high' | 'medium' | 'low';
      description: string;
      suggestion?: string;
    }>;
    summary: string;
  };

  /** Files created/modified by this agent */
  files?: string[];

  /** Additional custom metadata */
  [key: string]: any;
}

export interface AgentNodeData {
  /** Unique agent ID */
  id: string;

  /** Display name */
  name: string;

  /** Agent type (orchestrator, planning, IM, AR, RD, etc) */
  type: string;

  /** Current status */
  status: 'spawning' | 'planning' | 'active' | 'complete' | 'idle' | 'error';

  /** Parent agent ID (if any) */
  parentId?: string;

  /** X position (percentage 0-100) */
  x: number;

  /** Y position (percentage 0-100) */
  y: number;

  /** Child agent IDs */
  children: string[];

  /** Tree depth (0 = root) */
  depth?: number;

  /** Layer type */
  layer?: 'planning' | 'orchestrator' | 'agent';

  /** Agent metadata (thinking, code, output, etc) */
  metadata: AgentMetadata;
}

export interface TreeEdge {
  /** Parent node ID */
  from: string;

  /** Child node ID */
  to: string;

  /** Connection type (optional) */
  type?: string;
}

export interface TreeLayout {
  /** Canvas width when saved */
  width: number;

  /** Canvas height when saved */
  height: number;

  /** Zoom level (if implemented) */
  zoom?: number;

  /** Pan offset (if implemented) */
  panX?: number;
  panY?: number;
}

export interface TreeStructure {
  /** All agent nodes keyed by ID */
  nodes: Record<string, AgentNodeData>;

  /** Parent-child relationships */
  edges: TreeEdge[];

  /** Layout metadata */
  layout: TreeLayout;

  /** Timestamp when tree was captured */
  capturedAt: string;
}

export interface TaskExecutionResult {
  /** Execution status */
  success: boolean;

  /** Summary of work completed */
  summary: string;

  /** Quality score (if available) */
  quality_score?: number;

  /** Number of iterations */
  iterations?: number;

  /** Total execution time (seconds) */
  total_time?: number;

  /** Artifacts created */
  artifacts?: string[];

  /** Error message (if failed) */
  error?: string;
}

export interface TaskTreeSnapshot {
  /** Unique task ID */
  task_id: string;

  /** Task title/goal */
  title: string;

  /** Detailed task description */
  description?: string;

  /** Task status */
  status: 'pending' | 'planning' | 'executing' | 'completed' | 'failed';

  /** When task was created */
  created_at: string;

  /** When task was completed */
  completed_at?: string;

  /** Complete tree structure with all agent data */
  tree_structure: TreeStructure;

  /** Execution result */
  result?: TaskExecutionResult;

  /** Project this task belongs to */
  project?: string;
}

/**
 * Helper function to create an empty tree structure
 */
export function createEmptyTreeStructure(): TreeStructure {
  return {
    nodes: {},
    edges: [],
    layout: {
      width: 1200,
      height: 800,
    },
    capturedAt: new Date().toISOString(),
  };
}

/**
 * Helper function to validate a task tree snapshot
 */
export function validateTaskTreeSnapshot(snapshot: any): snapshot is TaskTreeSnapshot {
  return (
    snapshot &&
    typeof snapshot === 'object' &&
    typeof snapshot.task_id === 'string' &&
    typeof snapshot.title === 'string' &&
    typeof snapshot.status === 'string' &&
    typeof snapshot.created_at === 'string' &&
    snapshot.tree_structure &&
    typeof snapshot.tree_structure.nodes === 'object' &&
    Array.isArray(snapshot.tree_structure.edges)
  );
}
